language: python
python:
- 3.7.9
install:
- pip install flask
script:
- python -m unittest -v test
deploy:
- provider: heroku
  api_key: "$HEROKU_API_KEY"
  edge: true
  app: devopslab-paulo
  on:
    branch: main
- provider: gae
  keyfile: "../gcp.json"
  project: labdevopscloud-paulojr
  on:
    branch: main
before_install:
- openssl aes-256-cbc -K $encrypted_255346babcd1_key -iv $encrypted_255346babcd1_iv
  -in gcp.json.enc -out ../gcp.json -d
